name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: check-ins-autoconf
      run: command -v autoupdate &>/dev/null || apt install -y autoconf
    - name: check-ins-automake
      run: command -v aclocal &>/dev/null || apt install -y automake
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j
    - name: make check
      run: make check -j
    - name: make distcheck
      run: make distcheck -j
